# Generated by Django 3.0 on 2019-12-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mugshot',
            field=models.ImageField(default='images/user-icon.png', help_text='User profile image', upload_to='images/'),
        ),
    ]
