# Generated by Django 3.0 on 2020-01-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A memorable title for your trip.', max_length=600, unique=True)),
                ('slug', models.CharField(blank=True, editable=False, help_text='Unique URL path to access this trip.Computer Generated.', max_length=600)),
                ('address', models.CharField(blank=True, help_text="What's the full address of the airport?", max_length=1000)),
            ],
        ),
    ]
