# Generated by Django 3.0 on 2020-01-09 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airportaddress',
            old_name='address',
            new_name='location',
        ),
    ]
