# Generated by Django 3.0 on 2019-12-24 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A memorable title for your trip.', max_length=600, unique=True)),
                ('slug', models.CharField(blank=True, editable=False, help_text='Unique URL path to access this note.Computer Generated.', max_length=600)),
                ('arrive_at', models.CharField(blank=True, max_length=600)),
                ('terminal', models.CharField(choices=[('G', 'International Terminal G'), ('A', 'International Terminal A'), ('2D', 'Terminal 2'), ('1B', 'Harvey Milk Terminal 1B'), ('1C', 'Harvey Milk Terminal 1C'), ('3', 'Terminal 3')], help_text='Check https://www.flysfo.com/flight-info/airlines-at-sfo to see which Terminal you need to check in at for your flight.', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this note was created. Auto-generated.')),
                ('passenger', models.ForeignKey(help_text='The user making this journey.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
