# Generated by Django 3.0 on 2019-12-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='terminal',
            field=models.CharField(choices=[('G', 'International Terminal G'), ('A', 'International Terminal A'), ('2D', 'Terminal 2'), ('1B', 'Harvey Milk Terminal 1B'), ('1C', 'Harvey Milk Terminal 1C'), ('3', 'Terminal 3')], help_text='Check https://www.flysfo.com/flight-info/airlines-at-sfo to see which  Terminal you need to check in at for your flight.', max_length=2),
        ),
    ]
