# Generated by Django 3.0 on 2019-12-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='arrive_at',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
