# Generated by Django 3.0 on 2019-12-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_arrive_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='terminal',
            field=models.CharField(choices=[('G', 'International Terminal G'), ('A', 'International Terminal A'), ('2', 'Terminal 2'), ('1B', 'Harvey Milk Terminal 1B'), ('1C', 'Harvey Milk Terminal 1C'), ('3', 'Terminal 3')], default='3', help_text='Where you must checkin for the flight.', max_length=2),
            preserve_default=False,
        ),
    ]
