# Generated by Django 3.0 on 2019-12-27 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='logo',
            field=models.ImageField(default='images/air-transport.png', help_text='Brand image of the airline.', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='airline',
            name='name',
            field=models.CharField(default='', help_text='Name of this airline.', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airline',
            name='slug',
            field=models.CharField(blank=True, editable=False, help_text='Unique URL path to access this airline.Computer Generated.', max_length=200),
        ),
        migrations.AddField(
            model_name='airline',
            name='verified',
            field=models.BooleanField(default=True, help_text='Staff-checked for credibility.'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], help_text="On a scale from 1-5, with 1 meaning 'terrible' and 5 meaning 'exceptional', how would you rate your experience with this airline?")),
                ('price', models.DecimalField(decimal_places=2, help_text='How much did you pay this airline?', max_digits=9)),
                ('comments', models.TextField(help_text='What was your experience like? All feedback is encouraged!')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlines.Airline')),
                ('author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
