# Generated by Django 3.0 on 2019-12-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0002_auto_20191227_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline',
            old_name='name',
            new_name='title',
        ),
    ]
