# Generated by Django 3.0 on 2019-12-27 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0004_review_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='headline',
        ),
    ]
