# Generated by Django 3.0 on 2019-12-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0006_auto_20191228_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='headline',
            field=models.CharField(help_text='Headline for review.', max_length=200),
        ),
    ]
