# Generated by Django 3.0 on 2020-01-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0008_auto_20191228_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ticket_type',
            field=models.CharField(choices=[('One-Way', 'One-Way Ticket'), ('Round-trip', 'Round-Trip Ticket')], help_text='What type of ticket did you buy?', max_length=200, null=True),
        ),
    ]
